openapi: 3.0.0
info:
  version: 1.0.0
  title: Pokédex API
  description: A Simple Pokédex API for fetching, deleting and updating the Pokédex
servers:
  - url: https://pokedex-api-88gv.onrender.com/api

paths:
  /pokemon:
    get:
      summary: Get all of the Pokémon
      description: >-
        The get endpoint gives you an array of objects of all of the Pokémon
        entered in the API Database
      operationId: '1'
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ID:
                      type: number
                    name:
                      type: string
                    imgurl:
                      type: string
                    description:
                      type: string
                    primarytyping:
                      type: string
                    secondarytyping:
                      type: string
                    height:
                      type: number
                    weight:
                      type: number
